name: Convert MD to HTML using Pandoc

on:
  push:
    paths:
      - 'index.md'

jobs:
  convert:
    runs-on: ubuntu-latest
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Timestamp
        run: date --rfc-3339=seconds > lastBuild.txt

      - name: Convert Markdown to HTML
        run: |
          docker pull pandoc/core:latest
          docker run --volume "`pwd`:/data" --entrypoint "pandoc" pandoc/core:latest -s index.md -o index.html -c style.css

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          push: true
          default_author: github_actions
